### ISSUE TITLE
troubleshooting in executing the script

### ISSUE THREAD

**Issue by celesti0n** [inflex/ideviceunback#5]
hi there, 
Thank you so much for this, I'm really hoping the ideviceunback script will help me! Unfortunately there is something that doesn't seem to work. When I try to build the script, I get this message: 

/ideviceunback$ make
gcc -Wall -g ideviceunback.c sha1.o -o ideviceunback  -lsqlite3
ideviceunback.c:30:10: fatal error: sqlite3.h: No such file or directory
 #include <sqlite3.h>
          ^~~~~~~~~~~
compilation terminated.
Makefile:8: recipe for target 'ideviceunback' failed
make: *** [ideviceunback] Error 1

Please excuse me in advance if this is not the place to be posting such a message, as the problem I'm having might simply stem from my inexperience -- I am quite a newbie and not that fluent in programming, but I really could use the help! 

thanks again, 

celestion

**Comment by inflex** [comment]
You need to install the SQLite3 developer package 

If on ubuntu/debian;

  apt install libsqlite3-dev

**Comment by celesti0n** [comment]
thank you so much, it works!
