### ISSUE TITLE
Could not load SQLite3 (iOS 10+) manifest (/Users/jiangpeng/Desktop/bak/Manifest.db)

### ISSUE THREAD

**Issue by PengJiang520** [inflex/ideviceunback#8]
what fuck

**Comment by pabs3** [comment]
@PengJiang520 please be a bit more considerate when filing issues on open source projects created for free by volunteers in their spare time.

https://docs.github.com/github/site-policy/github-community-guidelines

Also, your report is missing some information. A log of what commands you ran, what output you got, what error you saw, what device the backup is from, what iOS version the device is running, what debugging you did to try and figure out the problem etc.

**Comment by PengJiang520** [comment]
sorry  iOS12 macOS Monterey 12.3.1 thank @pabs3

**Comment by pabs3** [comment]
@PengJiang520 What commands did you run? What exact error did you get? Please attach a text file containing the output of the commands.

**Comment by PengJiang520** [comment]
/ideviceunback -v -i /home/ubuntu/bak/bak/ -o /home/ubuntu/unbak/    thank @pabs3

**Comment by pabs3** [comment]
@PengJiang520 please copy the command and the full output of the command into a text file and attach it to this issue.

**Comment by PengJiang520** [comment]
This problem has been happening for a long time, I don't remember it, I solved it by changing the name of the folder @pabs3

**Comment by pabs3** [comment]
@PengJiang520 the name of the folder really shouldn't affect the
process, so I suggest you try to reproduce the issue, then reopen the
issue and attach a log of the command and its output when failing.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
